### PR TITLE
che-starter #316: Adding support of attributes in workspace config required for Che 7 support. Adding tests for che 7 / theia stacks

### PR DESCRIPTION
**Pull request by ibuziuk**
related issue - https://github.com/redhat-developer/che-starter/issues/316

### CODE REVIEW

**Comment by l0rd** [comment]
Yes I had the same problem when working with `chectl`. The URL in the response opens a GWT IDE. So I used [this regex](https://github.com/che-incubator/chectl/blob/master/src/helpers/che.ts#L209) to get the correct URL. 

Anyway it looks to me something that should be fixed upstream.

**Comment by garagatyi** [comment]
This REST link was added by request from IDE team a long time ago. So, no wonder that it is outdated.

**Comment by garagatyi** [comment]
By outdated I mean that it is designed to be compatible with the GWT IDE. We didn't think about theia back then

**Comment by ashumilova** [comment]
Workspace link has only GWT IDE location. From dashboard - we redirect to workspace-loader app and it decides which IDE to load in this method https://github.com/eclipse/che/blob/master/workspace-loader/src/index.ts#L348
So if there is server with type - "ide" (in case of Theia) - then its loaded, otherwise - GWT IDE from workspace links is loaded.
With new flow - really needs to be revised.

**Comment by ibuziuk** [comment]
@ashumilova @l0rd thanks for clarifications. I have created dedicated issue upstream - https://github.com/eclipse/che/issues/12376 
will IDE team be able to take it to the next sprint, or should I workaround this situation on che-starter side ?

**Comment by ashumilova** [comment]
Just a suggestion - maybe send from che-starter not to workspace ide link, but to workspace loader in the format: "workspace-loader/namespace/workspacename" and it will handle the IDEs?

**Comment by ibuziuk** [comment]
@ashumilova it is not that simple since it would require changes in fabric8-wit / fabric8-ui which are also fall back on the ide url send from che-starter which is than opened in the browser. So, the possible workaround would be similar to what @l0rd suggested in his comment above. However, the ideal solution would be fixing this problem upstream.

[1] https://github.com/redhat-developer/che-starter/pull/323#issuecomment-452782447

**Comment by ashumilova** [comment]
Yes, I mean nearly the same like here:
` ideURL.replace(/\/[^/|.]*\/[^/|.]*$/g, '\/dashboard\/#\/ide$&')`
but go to "`workspace-loader/namespace/workspacename`", cause this path "`dashboard/#/ide/namespace/workspacename`" also does the same under the hood.

**Comment by ibuziuk** [comment]
So, you mean `https://che.prod-preview.openshift.io/ibuziuk@redhat.com/che-starter-h7u51` would eventually become` https://che.prod-preview.openshift.io/workspace-loader/ibuziuk@redhat.com/che-starter-h7u51` ?

**Comment by ashumilova** [comment]
No, here are my workspace links:
screenshot from 2019-01-10 15-26-55
[following the regex](https://github.com/che-incubator/chectl/blob/master/src/helpers/che.ts#L209) transforms ide link `https://che.openshift.io/ashumilo/theia-evyv5` to 
`https://che.openshift.io/dashboard/#/ide/ashumilo/theia-evyv5`
I was proposing to change regex that converts ide link to 
`https://che.openshift.io/workspace-loader/ashumilo/theia-evyv5`

**Comment by ashumilova** [comment]
Sorry, @ibuziuk , you were right about :
`https://che.prod-preview.openshift.io/ibuziuk@redhat.com/che-starter-h7u51` 
if taken as an example from this [comment](https://github.com/redhat-developer/che-starter/pull/323#issuecomment-452736290)
it trasnforms to 
`https://che.prod-preview.openshift.io/workspace-loader/ibuziuk@redhat.com/che-starter-h7u51`

**Pull request merged**
