### PR TITLE
Removed workspace template files

### LINKED ISSUE #69: Model the workspace creation request using DTOs instead of a template
This will allow for more flexibility and future-proofing.

### PR DESCRIPTION
**Pull request by mlabuda**
fixes #69

### CODE REVIEW

**Comment by ibuziuk** [comment]
@mlabuda one thing I missed from previous PR - how Platform is supposed to get the workspace url from che-starter response ?

**Comment by ibuziuk** [comment]
[test]

**Comment by mlabuda** [comment]
Yeah this is something we are missing. We did getWorkspaceIDEURL but we did not process it further, I think. We should create issue for this.

**Comment by ibuziuk** [comment]
@mlabuda could you please create one ?

**Pull request merged**
