### PR TITLE
ISSUE-128, wait for workspace to stop before starting new workspace

### PR DESCRIPTION
**Pull request by sbryzak**
Signed-off-by: Shane Bryzak <sbryzak@redhat.com>

### CODE REVIEW

**Comment by ibuziuk** [comment]
@sbryzak could you please clarify how this PR was tested ?

**Comment by mlabuda** [comment]
Ok, fix for waiting on stoppped WS can be applied. But we probably will still need another PR or at least check OpenShift resources on their state, whether we are good or not.

**Comment by ibuziuk** [comment]
@mlabuda sure thing

**Comment by sbryzak** [comment]
Created a new pull request here: 

https://github.com/redhat-developer/che-starter/pull/147

**Pull request merged**
