### PR TITLE
che #214 Skip importing a project but save it to ws-config during workspace creation

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
issue https://github.com/redhat-developer/che-starter/issues/214

### CODE REVIEW

**Comment by ibuziuk** [comment]
@eivantsov could you please review

**Comment by ibuziuk** [comment]
cc: @rhopp

**Comment by benoitf** [comment]
it's not prompting the user that project is not imported when the workspace is started and then it's imported after clicking ?

**Comment by ibuziuk** [comment]
> it's not prompting the user that project is not imported when the workspace is started and then it's imported after clicking ?

@benoitf I was able to reproduce it only once. In other cases the project was imported automatically without extra actions from user side

**Comment by eivantsov** [comment]
@benoitf this is how workspaces with projects are started in upstream Che from User Dashboard. If there are projects in ws config and these projects are missing on the file system, the IDE imports them. If projects are there, nothing is done. If projects are there but missing in ws config, a project is first marked as misconfigured and then the IDE makes it blank and saves to ws config.

**Comment by benoitf** [comment]
@eivantsov well this "new way" has been introduced in upstream by being hijacked under the name 'show 'progress' of importing projects (also by removing my review on https://github.com/eclipse/che/pull/5934) this is why I was not up-to-date

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
tests are passing 
@benoitf @eivantsov are you ok to merge ?

**Comment by eivantsov** [comment]
Yeah, this way of importing projects is safer, and che-starter puts more responsibility on the IDE.

**Pull request merged**
