### PR TITLE
Split out configMap to make prod deployment easier

### PR DESCRIPTION
**Pull request by vpavlin**
new PR based on discussion in https://github.com/redhat-developer/che-starter/pull/96

### CODE REVIEW

**Comment by vpavlin** [comment]
Hmm..looking at it, the configMap does not need to be Template, what do you think @kbsingh

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@vpavlin should I merge the PR in the current state, or there will be some improvements ?

**Comment by vpavlin** [comment]
Removed the template wrapper from configMap, so no, it should be done now

**Comment by ibuziuk** [comment]
@vpavlin thanks for PR - merging

**Pull request merged**
