### PR TITLE
Che starter needs to update tenant if user provisioned with multi-tenant che-server, but still has single-tenant che deployment in namespace

### PR DESCRIPTION
**Pull request by ibuziuk**
Che starter needs to update tenant if user provisioned with multi-tenant che-server, but still has single-tenant che deployment in namespace

### CODE REVIEW

**Comment by ibuziuk** [comment]
@aslakknutsen @l0rd @davidfestal this is not tested draft, but just to make sure we wanted to have smth. like this, right ?

**Comment by davidfestal** [comment]
seems to me like what we want.

**Comment by ibuziuk** [comment]
How che-starter is expected to work in case when user provisioned with multi-tenant che-server, but still has single-tenant che deployment in namespace:

- User navigates to Codebases UI
- UI sends request to in order to GET che-server state
- che-starter knows that there is still che-server deployment in user-namespace and calls update tenant, but will still reply to UI that che-server is **not** ready - user provisioned with multi-tenant che-server, but still has single-tenant che deployment in namespace -  https://github.com/redhat-developer/che-starter/pull/245/files#diff-cf8fe0a91f69533a082c93186c0b65e5R57
- on the next UI request che-server deployment will likely be removed and multi-tenant che-server URL will be returned - https://github.com/redhat-developer/che-starter/pull/245/files#diff-cf8fe0a91f69533a082c93186c0b65e5R60

**Comment by l0rd** [comment]
@ibuziuk your implementation looks coherent with what we have discussed this morning.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@davidfestal merging this PR and will add extra logic with label processing if migration failed later, if needed

**Comment by davidfestal** [comment]
sure !

**Pull request merged**
