### PR TITLE
[Proposal] with some improvements for the docker image generation

### PR DESCRIPTION
**Pull request by hectorj2f**
I think we should get the `GET_GITHUB_TOKEN` and `GET_OPENSHIFT_TOKEN` variables as ENV variables that can change depending of many things (e.g. target env, changes in KC endpoints,...)

I believe we don't need anymore to install the certificate into the Java keystore. We saw that doing it didn't fix our SSL problem. Also, we don't seem to interact with any other domain name which requires the installation of its cert. That is why I decided to install it a runtime using ENV variables which can allow us to move from infraA to infraB without changing this code.

ping @ibuziuk @aslak

### CODE REVIEW

**Comment by ibuziuk** [comment]
@hectorj2f thanks for PR!
I like the idea of ENV vars for Keycloak endpoints, but:

1. Could those vars be set  in Dockerfile (I guess if PR is merged now che-starter prod-preview will be broken because no vars are set) ?
2. Could we fall back on default endpoints if no ENV VAR set ?
- http://sso.prod-preview.openshift.io/auth/realms/fabric8/broker 

WDYT ?

P.S. there is an issue for making keycloak endpoints more generic in che-starter - https://github.com/redhat-developer/che-starter/issues/31

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@hectorj2f I think spring way of setting those ENV vars would be smth. like:

`
    @Value("${GITHUB_TOKEN_URL:http://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/openshift-v3/token}")
`

**Comment by hectorj2f** [comment]
@ibuziuk Yeah I agree on having defaults at code level. Feel free to push any modifications to this PR.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@hectorj2f Thanks! merged to master

**Comment by ibuziuk** [comment]
@hectorj2f @aslakknutsen  even though the change works locally on prod-preview I keep getting:

`java.io.FileNotFoundException: /opt/che-starter/tsrv.devshift.net.cer (No such file or directory)`

Any ideas why this might happen ?

**Comment by ibuziuk** [comment]
@hectorj2f the only sufficient difference in comparison with the previous approach is that install certificate script is run from ENTRYPOINT

**Comment by hectorj2f** [comment]
@ibuziuk I am sending a PR with the fix. It was related to the permissions inside the directory

**Pull request merged**
