### PR TITLE
CHE-35: Adding 'Namespace' parameter

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by ibuziuk** [comment]
@mlabuda could you please review ?
I have also changed formatting because we do not use tabs in the project

**Comment by ibuziuk** [comment]
@mlabuda thanks for review. I have also changed route name to 'che-host' because it is used in fabric8 template[1]. Are you ok with it ?

[1] http://central.maven.org/maven2/io/fabric8/online/apps/che/1.0.54/

**Comment by mlabuda** [comment]
Well default route created by OpenShift is "che". The "che-host" route is the one created manually by exposing service and mapping it to minishift. But I am ok with that. I think we could/should do it more robust and to autodetect route for che server.

**Comment by ibuziuk** [comment]
> Well default route created by OpenShift is "che"

@mlabuda could you ellaborate why it is default ? "che-host" route is not created manually, it is created automatically by the template while exposing che-host service - http://central.maven.org/maven2/io/fabric8/online/apps/che/1.0.54/che-1.0.54-openshift.yml

**Comment by mlabuda** [comment]
In the yml file, there is defined route with name "che" which is bound to service che-host:
`- apiVersion: v1
  kind: Route
  metadata:
    labels:
      provider: fabric8
      project: che
      version: 1.0.54
      group: io.fabric8.online.apps
    name: che
  spec:
    to:
      kind: Service
      name: che-host`

When I was deploying Che to minishift, I saw somewhere creating a mapping to che.openshift.mini. I dont recall where it was. I have running Che on minishift from fabric8 template, but I have not updated it for ~1 week. And I have following routes:
che        che-che.192.168.99.100.xip.io             che-host   <all>     
che-host   che.openshift.mini                        che-host   http   
as you can see che-host is create with the mapping, what had to be done manually

**Comment by ibuziuk** [comment]
hmm... with the latest script that uses nip.io for route I have che-host only

`che-host                               che.192.168.42.151.nip.io                                           che-host:http                                        expose=true,project=che,provider=fabric8`

Ok, I will probably need to update documentation for testing against minishift. Please, feel free to reopen if needed

**Pull request merged**
