### PR TITLE
che #168: Setting GitHub token during workspace startup

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### CODE REVIEW

**Comment by l0rd** [comment]
@ibuziuk LGTM but if it's not needed for summit (i.e. the original problem is not reproducible after idling has been disabled) I would wait until Wed to merge it.

**Comment by ibuziuk** [comment]
@l0rd agree, just need to bear this situation in mind and treat it as a "known bug" (deployment could be scaled down accidentally etc.)

**Comment by gorkem** [comment]
Can you point me to the tests that are testing this case?

**Comment by ibuziuk** [comment]
There is an integration test against tsrv cluster which is currently ignored - https://github.com/redhat-developer/che-starter/blob/master/src/test/java/io/fabric8/che/starter/client/GitHubTokenClientTest.java#L41
I need to update che-server to enable it

**Comment by ibuziuk** [comment]
@l0rd @gorkem after tsrv update to the latest verion of template 1.0.146 I got a bunch of test failures due to keykloak support (which is expected). Could you point me to the latest image of che-server without keycloak enabled ?

**Comment by l0rd** [comment]
f535efe-fabric8-a22ff93

**Comment by ibuziuk** [comment]
Thanks, Mario - che-server for integration tests on tsrv cluster has been updated and test for setting github token is now enabled

**Comment by ibuziuk** [comment]
Adding test for setting committer info (email & name) and checking if preference update was successful

**Comment by ibuziuk** [comment]
[test]

**Pull request merged**
