### PR TITLE
Adding NewLineAtTheEnd rule to checkstyle

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### CODE REVIEW

**Comment by ibuziuk** [comment]
@mlabuda FYI, adding some checkstyle rules ;-)

**Comment by mlabuda** [comment]
Hopefully those won't make me unhappy ;) I use default Eclipse formatting, it would be good to align somehow rules based on ours preferences.

**Comment by ibuziuk** [comment]
@mlabuda well, I hope you will not be unhappy if we would use spaces only ?

**Comment by mlabuda** [comment]
Well, I can live with that, I will set replacing spaces for tabs. 4 spaces bounce for each nesting?

**Comment by ibuziuk** [comment]
@mlabuda yup, anyway I have not add any rules for that - for now it's only package names & line at the end check. I will provide another PR with line rules which we could discuss

**Pull request merged**
