### PR TITLE
Add ITest for agents/installers present in Stack to StackClientTest

### PR DESCRIPTION
**Pull request by rhopp**
Signed-off-by: Radim Hopp <rhopp@redhat.com>

### CODE REVIEW

**Comment by rhopp** [comment]
[test]

**Comment by ibuziuk** [comment]
`WorkspaceClientTest.createAndStartWorkspaceWhenThereIsAlreadyOneRunning:124 expected:<[STOPPED]> but was:<[RUNNING]>`
@rhopp it looks like there is a problem with starting new workspace when there is already one running

**Comment by ibuziuk** [comment]
[test]

**Comment by rhopp** [comment]
Formatting fixed. Investigating test failure.

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
@ibuziuk The failure seemed like some intermittent issue. The problem was already in starting the first workspace in that test... It failed to start. 
logs:
```
{"@timestamp":"2018-03-08T10:44:43.286+00:00","@version":1,"message":"Workspace 'kkanova-osiotest1/tjouy' with id 'workspacelacags2sbkrn5hxp' created by user 'kkanova-osiotest1'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"http-nio-8080-exec-6","level":"INFO","level_value":20000,"req_id":"","identity_id":"e1eb28b1-e841-4edf-8179-44b2404a8519"}
{"@timestamp":"2018-03-08T10:44:43.948+00:00","@version":1,"message":"Starting workspace 'kkanova-osiotest1/tjouy' with id 'workspacelacags2sbkrn5hxp' by user 'kkanova-osiotest1'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"http-nio-8080-exec-10","level":"INFO","level_value":20000,"req_id":"","identity_id":"e1eb28b1-e841-4edf-8179-44b2404a8519"}
{"@timestamp":"2018-03-08T10:44:44.172+00:00","@version":1,"message":"Failed to start Kubernetes runtime of workspace workspacelacags2sbkrn5hxp. Cause: Failure executing: POST at: https://f8osoproxy-test-dsaas-preview.b6ff.rh-idev.openshiftapps.com/api/v1/namespaces/kkanova-osiotest1-che/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods \"workspacelacags2sbkrn5hxp.dockerimage\" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=4,limits.memory=2147483648, used: limits.cpu=4,limits.memory=2147483648, limited: limits.cpu=4,limits.memory=2560Mi.","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-0","level":"WARN","level_value":30000,"req_id":"","identity_id":"e1eb28b1-e841-4edf-8179-44b2404a8519"}
{"@timestamp":"2018-03-08T10:44:44.427+00:00","@version":1,"message":"Workspace 'kkanova-osiotest1:tjouy' with id 'workspacelacags2sbkrn5hxp' start failed","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"WorkspaceSharedPool-0","level":"INFO","level_value":20000,"req_id":"","identity_id":"e1eb28b1-e841-4edf-8179-44b2404a8519"}
```

**Comment by ibuziuk** [comment]
@rhopp yeah, need to investigate those random failures...

**Pull request merged**
