### PR TITLE
Revert "che #113 Fixing project type"

### LINKED ISSUE #113: Type of created project is wrong

### PR DESCRIPTION
**Pull request by mlabuda**
This reverts commit 20f170b323338e9bec3a7d1f555d4685e70b9425.

fixes #113

### CODE REVIEW

**Comment by mlabuda** [comment]
[test]

**Comment by ibuziuk** [comment]
@mlabuda could we have both 'project' & 'projectType' set simultaneously ?

**Comment by mlabuda** [comment]
Yes, this seems to be an option for both of us :)

**Comment by ibuziuk** [comment]
@mlabuda closing in favour of https://github.com/redhat-developer/che-starter/pull/129

**Pull request closed without merging**
