### PR TITLE
[WIP] Add prod OpenShift template

### PR DESCRIPTION
**Pull request by vpavlin**
I am adding a new file because the default values and especially the image is different. If you think we can merge the 2 templates, let me know and I am happy to do it. 

The main issue is that until registry.devshift is open to public, just plainly importing the template would not work and people would need to edit image manually.

### CODE REVIEW

**Comment by ibuziuk** [comment]
@vpavlin why do we need prod template in che-starter ? I thought that all template handling is happening in "housekeeping" project and @kbsingh said that we should not make any references to free int publicly.
The template in che-starter is just for local testing against minishift, so I do not see sense to have a prod template in the project. WDYT ?

**Comment by kbsingh** [comment]
@ibuziuk we are moving the content up into the code repos, to give you better control over it, and for you to not need to wait on housekeeping PR's etc; We would then just maintain a list of these deployment configs, along with which repo it coms from etc.

**Comment by kbsingh** [comment]
I would recommend moving the OPENSHIFT endpoint details to a secret or configmap and set defaults that work for local development, rather than production endpoints. We can then manage the secret in prod / stage/ dev as needed.

**Comment by ibuziuk** [comment]
@kbsingh thanks for clarification. I have created a separate issue for adding secret / configmap [1]. But am I correct that che-starter deployment to prod-preview is still going to use template from housekeeping ? 

[1] https://github.com/redhat-developer/che-starter/issues/97

**Comment by ibuziuk** [comment]
[test]

**Comment by vpavlin** [comment]
Let me split the secret out

**Comment by vpavlin** [comment]
@ibuziuk One thing I am not sure about is which image to put there, I think it might be best if I add image as a parameter so that you can have developer default and we can replace it with devshift

**Comment by ibuziuk** [comment]
@vpavlin would be awesome

**Pull request closed without merging**
