### PR TITLE
che #81 Returning WorkspaceLink from create Workspace API

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by ibuziuk** [comment]
@mlabuda could you please review ? For me workspace is created just fine: 
```
{
  "href": "http://che.192.168.42.126.nip.io/che/zkren1m2",
  "rel": "ide url",
  "method": "GET"
}
```

However, I am getting issues with project creation - 503 service is unavailable:
```
2017-03-28 19:26:06.246  INFO 20469 --- [cTaskExecutor-2] i.f.c.s.c.ProjectClient                  : Creating project against workspace agent URL: http://wsagent.v2o1ryh71ln3hisd.che.192.168.42.126.nip.io/api/project/batch
2017-03-28 19:26:06.916 ERROR 20469 --- [cTaskExecutor-2] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected error occurred invoking async method 'public void io.fabric8.che.starter.client.ProjectClient.createProject(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException,io.fabric8.che.starter.exception.ProjectCreationException'.

org.springframework.web.client.HttpServerErrorException: 503 Service Unavailable
```
Can you repro the same ?

**Comment by mlabuda** [comment]
Yeah, I think it will be related to missing SSH agent. I tried also remove terminal, which could use SSH, but it did not help. See error on Che server side
```Error of injection public ssh keys. mkdir: cannot create directory '//.ssh/': Permission denied

[STDOUT] Terminal Agent will be downloaded from Workspace Master

[STDERR] mkdir: cannot create directory '//che': Permission denied

[STDERR] 

[STDERR] gzip: stdin: unexpected end of file

[STDERR] tar: Child returned status 1

[STDERR] tar: Error is not recoverable: exiting now

[STDERR] /bin/sh: line 177: //che/terminal/che-websocket-terminal: No such file or directory```

**Comment by ibuziuk** [comment]
@mlabuda but it used to work before the workspace template removal - https://drive.google.com/file/d/0B_2DS3FBL8MFWmZHeTJKZkxDY0k/view

**Comment by mlabuda** [comment]
Ok problem was in timeout for workspace creation, I will create another issue to track and fix it. This one is good to merge.

**Comment by ibuziuk** [comment]
timeout issue - https://github.com/redhat-developer/che-starter/issues/83

**Pull request merged**
