### PR TITLE
che #145: Increasing router timeout to 3 mins

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### CODE REVIEW

**Comment by ibuziuk** [comment]
Can not test on free-int due to the insufficient memory while che-server deployment:
`pod (che-1-deploy) failed to fit in any node fit failure summary on nodes : Insufficient memory (2), Insufficient pods (3), MatchNodeSelector (2)`

**Comment by mlabuda** [comment]
Have you tried it at least on minishift?

**Comment by ibuziuk** [comment]
trying against prod...

**Comment by ibuziuk** [comment]
@mlabuda does not work on against prod :/

**Comment by ibuziuk** [comment]
@mlabuda setting client timeout also doesn't help: 
```
Environment Variables:
      GITHUB_TOKEN_URL:			<set to the key 'github.tokenurl' of config map 'che-starter'>
      OPENSHIFT_TOKEN_URL:		<set to the key 'oso.tokenurl' of config map 'che-starter'>
      OSO_ADDRESS:			<set to the key 'oso.address' of config map 'che-starter'>
      OSO_DOMAIN_NAME:			<set to the key 'oso.domain.name' of config map 'che-starter'>
      KUBERNETES_CERTS_CA_FILE:		<set to the key 'kubes.certs.ca.file' of config map 'che-starter'>
      ROUTER_DEFAULT_SERVER_TIMEOUT:	180s
      ROUTER_DEFAULT_CLIENT_TIMEOUT:	180s
```

**Comment by ibuziuk** [comment]
still works fine if I run che-starter via 

`docker run -p 10000:10000 -t rhche/che-starter`

**Comment by kbsingh** [comment]
when running in minishift, are you able to check the ENV's in the terminal for the pod ? are they being set to what you expect it to be ?

**Comment by kbsingh** [comment]
@ibuziuk how are you trying it against prod ? how did you get this edit into the deployment there ?

**Comment by ibuziuk** [comment]
@kbsingh Both env vars are set correctly according to pod's terminal output:

```
sh-4.2$ echo $ROUTER_DEFAULT_SERVER_TIMEOUT                                                                 
180s                                                                                                        
sh-4.2$ echo $ROUTER_DEFAULT_CLIENT_TIMEOUT                                                                 
180s                
```                                                                                        
In terms of testing, I just run che-starter locally and use it's API for starting che-server on prod by pointing masteURL to prod cluster.

**Comment by ibuziuk** [comment]
oc annotate approach also does not work:
`oc annotate route che-starter --overwrite haproxy.router.opensfhit.io/timeout=180s`
Actually when I set it to 2s the execution time before getting 504 is pretty much the same ~ 30 secs

**Comment by ibuziuk** [comment]
`oc annotate` approach actually works just fine, there is a typo in the docs - https://docs.openshift.com/container-platform/3.3/install_config/configuring_routing.html#install-config-configuring-route-timeouts

`s/opensfhit.io/openshift.io`

**Comment by ibuziuk** [comment]
Closing. `oc annotate route che-starter --overwrite haproxy.router.opensfhit.io/timeout=180s` works fine - the only problem that there is no che-starter route on prod...

**Pull request closed without merging**
