### PR TITLE
Fixed DTO to be representative of che-server DTO

### LINKED ISSUE #261: Fix WorkspaceConfig model - environments are not getting mapped correctly
* Expected:  
```
...
"environments": {
  "defaultEnv": {
    "recipe" : ...,
    "machines" : { ... }
  }
},
"defaultEnv": "defautEnv",
...
```

* Actual:  
```
...
"environments": {
  "defaultEnv": null
},
"defaultEnv": "default",
...
```

Model is expecting an environment with name `defaultEnv`, when an actual environment with name `default` is received by the server, it does not get mapped and the environments contains `null`

### PR DESCRIPTION
**Pull request by ScrewTSW**
Closes #261

### CODE REVIEW

**Comment by ScrewTSW** [comment]
@ibuziuk Should be safe to merge once tests finish

**Comment by ibuziuk** [comment]
@ScrewTSW does the default env var is set correctly when you do list workspaces for example e.g.

```
"environments": {
        "default": {
          "recipe": {
            "type": "dockerimage",
            "location": "registry.devshift.net/che/wildfly-swarm",
            "contentType": null,
            "content": null
          },
          "machines": {
            "dev-machine": {
              "agents": [
                "org.eclipse.che.terminal",
                "org.eclipse.che.ws-agent",
                "com.redhat.bayesian.lsp",
                "org.eclipse.che.exec"
              ],
              "attributes": {
                "memoryLimitBytes": "2147483648"
              }
            }
          }
        }
      },
```

**Comment by ScrewTSW** [comment]
@ibuziuk yes, `WorkspaceConfig.defaultEnv = "default"` when 
```
"environments": {
  "default": { ... }
}
```  
is present

**Comment by ibuziuk** [comment]
@ScrewTSW approved. feel free to merge

**Pull request merged**
